# TRMNLP configuration
# {{ env.VARIABLE }} interpolation is available here
---
# auto-reload when files change (`watch: false` to disable)
watch:
  - .trmnlp.yml
  - src

# values of custom fields (defined in src/settings.yml)
custom_fields: {
  list_name: "Shopping List",
}

# override variables
variables:
  trmnl: {}
  reminders:
    - idx: 1
      date: ""
      title: "Breakfast bars"
      num_tasks: 0
      description: ""
    - idx: 2
      date: ""
      title: "Cheese & Crackers"
      num_tasks: 0
      description: ""
    - idx: 3
      date: ""
      title: "Cherry tomatoes"
      num_tasks: 0
      description: ""
    - idx: 4
      date: ""
      title: "Dogfood"
      num_tasks: 0
      description: ""
    - idx: 5
      date: ""
      title: "Mini cucumbers"
      num_tasks: 0
      description: ""
    - idx: 6
      date: ""
      title: "Peanut butter"
      num_tasks: 0
      description: ""
    - idx: 7
      date: ""
      title: "Rice cups"
      num_tasks: 0
      description: ""
    - idx: 8
      date: ""
      title: "Smoked almonds"
      num_tasks: 0
      description: ""
    - idx: 9
      date: ""
      title: "Sweet chilli sauce"
      num_tasks: 0
      description: ""
    - idx: 10
      date: ""
      title: "Tuna"
      num_tasks: 0
      description: ""
    - idx: 11
      date: ""
      title: "Yoghurt"
      num_tasks: 0
      description: ""
    - idx: 12
      date: ""
      title: "Bananas"
      num_tasks: 0
      description: ""
    - idx: 13
      date: ""
      title: "Milk"
      num_tasks: 0
      description: ""
    - idx: 14
      date: ""
      title: "Eggs"
      num_tasks: 0
      description: ""
    - idx: 15
      date: ""
      title: "Bread"
      num_tasks: 0
      description: ""
    - idx: 16
      date: ""
      title: "Apples"
      num_tasks: 0
      description: ""
    - idx: 17
      date: ""
      title: "Toilet paper"
      num_tasks: 0
      description: ""
    - idx: 18
      date: ""
      title: "Pasta"
      num_tasks: 0
      description: ""
    - idx: 19
      date: ""
      title: "Shampoo"
      num_tasks: 0
      description: ""
    - idx: 20
      date: ""
      title: "Orange juice"
      num_tasks: 0
      description: ""
